In [1]:
import torch
import gen_nms
from gen_nms.ops.boxes import diou_nms, batched_diou_nms

boxes = torch.tensor([
    [0.0, 0.0, 10.0, 10.0],
    [1.0, 1.0, 11.0, 11.0],
    [50.0, 50.0, 60.0, 60.0],
], dtype=torch.float32)

scores = torch.tensor([0.9, 0.8, 0.7], dtype=torch.float32)
labels = torch.tensor([0, 0, 1], dtype=torch.int64)

keep_raw = torch.ops.gen_nms.diou_nms(boxes, scores, 0.5)
keep_wrap = diou_nms(boxes, scores, 0.5)
keep_batch = batched_diou_nms(boxes, scores, labels, 0.5)

print("raw:", keep_raw)
print("wrapper:", keep_wrap)
print("batched:", keep_batch)

raw: tensor([0, 2])
wrapper: tensor([0, 2])
batched: tensor([0, 2])


In [6]:
import torch
import gen_nms

op = torch.ops.gen_nms.diou_nms.default

boxes = torch.tensor([
    [0.0, 0.0, 10.0, 10.0],
    [1.0, 1.0, 11.0, 11.0],
    [50.0, 50.0, 60.0, 60.0],
], dtype=torch.float32)
scores = torch.tensor([0.9, 0.8, 0.7], dtype=torch.float32)

torch.library.opcheck(op, (boxes, scores, 0.5))
print("opcheck passed")

OpCheckError: opcheck(op, ...): test_faketensor failed with gen_nms.diou_nms.default (scroll up for stack trace)

In [4]:
import time
import torch
import gen_nms

N = 2000
boxes = torch.rand(N, 4)
boxes[:, 2:] = boxes[:, :2] + torch.rand(N, 2) * 0.2
scores = torch.rand(N)

t0 = time.time()
for _ in range(50):
    torch.ops.gen_nms.diou_nms(boxes, scores, 0.5)
print("avg sec/call:", (time.time() - t0) / 50)

avg sec/call: 0.019492979049682616


In [7]:
import torch
import gen_nms
from gen_nms.ops.boxes import diou_nms, batched_diou_nms

boxes = torch.tensor([
    [0.0, 0.0, 10.0, 10.0],
    [1.0, 1.0, 11.0, 11.0],
    [50.0, 50.0, 60.0, 60.0],
], dtype=torch.float32)

scores = torch.tensor([0.9, 0.8, 0.7], dtype=torch.float32)
labels = torch.tensor([0, 0, 1], dtype=torch.int64)

print(torch.ops.gen_nms.diou_nms(boxes, scores, 0.5))
print(diou_nms(boxes, scores, 0.5))
print(batched_diou_nms(boxes, scores, labels, 0.5))

tensor([0, 2])
tensor([0, 2])
tensor([0, 2])
